apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simplenginx
  name: simplenginx
  namespace: saleh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplenginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}